workspace = { members = ["crates/riscv-cpu"] }

[package]
name = "yove"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-cpu = { path = "crates/riscv-cpu" }
goblin = { version = "0.7.1", features = [ "elf32" ]}
